---
title: "Research"
output:
  html_document:
    toc: true
    toc_float: true
---

```{css, echo=FALSE}
a:link {text-decoration: none;}
```

I am a PhD student in [Bioinformatics and Statistical Learning Group](https://tsenglab.biostat.pitt.edu) under the guidance of [Dr. George C. Tseng](http://www.pitt.edu/~ctseng/) at University of Pittsburgh, and interested in application of data science in genomics and development of statistical tools for biological study.


## Research Project
### Ongoing Project
* Cluster number and penalty parameter selection for (sparse) Gaussian mixture model
* Multi-class concordance analysis
* Multi-omics data analysis for patients with breast cancer before and after hormone therapy
* Analysis of the microenviroment for patients with breast cancer and brain metastasis

### Collaboration
* Great Lakes Breast Cancer Consortium data analysis
* Outcomes After Sentinel Lymph Node Biopsy and Radiotherapy in Older Women With Early-Stage, Estrogen Receptor–Positive Breast Cancer

### Methodology
* Congruence analysis between cell lines and human tissues
* Constrained Gaussian mixture model


## Publication
#. **Jian Zou**&dagger;, Yannick Düren&dagger;, and Li-Xuan Qin* (2022). [<span style="color: grey;">PRECISION.seq: An R Package for Benchmarking Depth Normalization in microRNA Sequencing</span>](https://www.frontiersin.org/articles/10.3389/fgene.2021.823431/full), *Frontiers in Genetics* 12.
#. Neil Carleton, **Jian Zou**, Yusi Fang, ..., George C. Tseng, Oscar C. Marroquin, Adrian V. Lee\*, Priscilla F. McAuliffe\* (2021). [<span style="color: grey;">Outcomes After Sentinel Lymph Node Biopsy and Radiotherapy in Older Women With Early-Stage, Estrogen Receptor–Positive Breast Cancer</span>](https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2778563), *JAMA Network Open* 4(4): e216322-e216322.
#. Terrell E. Jones, **Jian Zou**, George C. Tseng, Somak Roy, Rohit Bhargava\* (2021). [<span style="color: grey;">The Utility of Next-Generation Sequencing in Advanced Breast and Gynecologic Cancers: Experience of a Large Tertiary Care Women's Hospital</span>](https://academic.oup.com/ajcp/article-abstract/156/3/455/6174439), *American Journal of Clinical Pathology* 156(3): 455-460.
#. Li-Xuan Qin\*, **Jian Zou**, Jiejun Shi, Ann Lee, Aleksandra Mihailovic, Thalia A. Farazi, Thomas Tuschl, Samuel Singer (2020). [<span style="color: grey;">Statistical Assessment of Depth Normalization for Small RNA Sequencing</span>](https://ascopubs.org/doi/10.1200/CCI.19.00118), *JCO Clinical Cancer Informatics* 4 (June): 567-582.
#. Peng Liu&dagger;, Silvia Liu&dagger;, Yusi Fang, Xiangning Xue, **Jian Zou**, George C. Tseng\*, Liza Konnikova\* (2020). [<span style="color: grey;">Recent Advances in Computer-assisted Algorithms for Cell Subtype Identification of Cytometry Data</span>](https://www.frontiersin.org/articles/10.3389/fcell.2020.00234/full), *Frontiers in Cell and Developmental Biology* 8 (April): 234.

### In preparation
#. **Jian Zou**, Yujia Li, George C. Tseng*. Cluster size constrained clustering.
#. **Jian Zou**, George C. Tseng*. Congruence analysis between cell lines and tumors.
#. Steffi Oesterreich\*&dagger;, Azadeh Nasrazadani\*&dagger;, **Jian Zou**&dagger;, Neil Carleton, Tiffany Onger, Matthew D Wright, Yujia Li, Kathryn Demanelis, Bhuvaneswari Ramaswamy, George Tseng, Adrian V. Lee, Nicole Williams\*, Megan Kruse\*. Comprehensive retrospective analysis of clinicopathological features and outcome comparing patients with invasive ductal and lobular breast cancer.
#. Wei Zong, Tanbin Rahman, Li Zhu, Xiangrui Zeng, Yingjin Zhang, **Jian Zou**, Song Liu, Zhao Ren, Jingyi Jessica Li, Steffi Osterreich, Tianzhou Ma, George C. Tseng\*. CAMO: A molecular congruence analysis framework for evaluating model organisms.


## Academic Presentation
* (Poster) CGMM: an algorithm for constrained model-based clustering, *2022 Symposium on Data Science & Statistics*, June 2022
* (Poster) Genomics congruence analysis to optimally select representative cell lines for breast cancer histological subtypes, *NISS Graduate Student Research Conference*, May 2022
* (Poster) CGMM: an algorithm for constrained model-based clustering, *ASA Pittsburgh Spring Banquet*, April 2022
* (Talk) Congruence analysis between cell lines and tumors, *Pitt Biostatistics Research Day*, March 2022
* (Poster) Outcomes After Sentinel Lymph Node Biopsy and Radiation Therapy in Elderly Women with Estrogen Receptor-Positive, Early Stage Breast Cancer, *Pitt GSPH Dean's Day*, April 2021.
* (Poster, 3rd author) Abstract PS11-02: Comprehensive comparative analysis of invasive ductal and lobular breast cancer cases in great lakes breast cancer consortium, *SABC*, Dec 2020.
* (Poster, 3rd author) Abstract PS1-10: Outcomes after sentinel lymph node biopsy and radiation therapy in women over 70 years old with ER+, HER2-, clinically node negative breast cancer, *SABC*, Dec 2020.
* (Talk) Statistical Assessment of Depth Normalization Methods for MicroRNA Sequencing, *ICSA (Hangzhou)*, Dec 2019.


## Award
* Student & Early Career Travel Award, *2022 Symposium on Data Science & Statistics*, April 2022
* The 2022 Mihaela Serban Award for Best Poster Presentation, *ASA Pittsburgh Chapter*, April 2022


## Teaching
* *Teaching Fellow*, Mathematical Methods for Statistics, Pitt Biostatistics, Fall 2021
* *Teaching Assistant*, Analysis of Categorical Data, Columbia Biostatistics, Summer 2018


## Selected Courses Taken
* Asymptotic Methods in Statistics, Pitt Statistics, Fall 2020
* Likelihood Theory and Applications, Pitt Biostatistics, Spring 2020
* Linear Models, Pitt Biostatistics, Fall 2019
* Statistical Estimation Theory, Pitt Biostatistics, Fall 2019
* Topics of Statistical Learning and Data Mining, Columbia Biostatistics, Fall 2018
* Introduction to Modern Analysis, Columbia Math, Summer 2018  
* Topics in Advanced Statistical Computing, Columbia Biostatistics, Spring 2018  
* Statistical Genetic Modeling, Columbia Biostatistics, Spring 2018
* Cell Biology, CCNU Life Science, Fall 2016
* Molecular Biology, CCNU Life Science, Fall 2016
* Genetics, CCNU Life Science, Spring 2015
* Biochemistry, CCNU Life Science, Spring 2015
* Organic Chemistry, CCNU Chemistry, Fall 2014
* Microbiology, CCNU Life Science, Fall 2014
